config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    # def isPublished
    #     return if created_at.blank?
    #     if Time.now > created_at
    #         return true
    #     end
    # end
    def published?
        created_at < Time.now
    end
    
    
    def increase_like
        self.increament!(:count_like)
    end
    
    #one to many
    has_many :texts
    has_many :images
end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, presence: true
    has_many :products
end

app/models/image.rb
class Image < ApplicationRecord
    default_scope { order(:position) }
    validates :headline, :url_image, :article, presence: true
    belongs_to :article
    def increase_like
        self.increament!(:count_like)
    end
end

app/models/product.rb
class Product < ApplicationRecord
    # enumerize
    extend Enumerize
    enumerize :level, in: [:easy, :medium, :hard], default: :easy
    enumerize :country, in: ISO3166::Country.translations, default: :DE

    # valides
    validates :title, :description, :price, presence: true

    validate :title_is_shorter_than_description
    

    def title_is_shorter_than_description
        return if title.blank? || description.blank?
        if description.length < title.length
            errors.add(:description,'can\'t be shorter than title' )
        end
    end

    # validate :price_is_number_and_always_present_and_more_than_0

    # def price_is_number_and_always_present_and_more_than_0
    #     if price <= 0 and price.present?
    #         errors.add(:price,'cant\t be smaller than 0 and price is a number')
    #     end
    # end

    # scope
    scope :published, -> {where(published: true)}
    scope :priced_more_than, -> (price) {where('price > ?',price)}
    scope :description_include, ->(description){where('description LIKE ? ',"%#{description}%")}

    # ActiveRecord life cycle hook
    before_save :strip_html_from_description, :set_title_lowercase

    def strip_html_from_description
        self.description = ActionView::Base.full_sanitizer.sanitize(self.description)
    end

    def set_title_lowercase
        self.title = title.downcase!
    end

    #one to many
    belongs_to :category

end

app/models/text.rb
class Text < ApplicationRecord
    default_scope { order(:position) }
    validates :headline, :sentence, :article, presence: true
    belongs_to :article
    def increase_like
        self.increament!(:count_like)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :setLocale
    def setLocale
      I18n.locale = params[:locale] if params[:locale].present?
    end
    before_action :authenticate_admin!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :product_params, only: [:create, :update]
    before_action :find_product, only: [:show, :edit, :update,:destroy]
    ### action index
    def index
        @products = Product.includes(:category).published
    end
    def show
    
    ### action new
    end
    def new
        @product = Product.new
    end

    ### action create
    def create
        @product =Product.new(product_params)
        unless @product.save
            flash.now[:notice] = messageFail(:create)
            return render :new
        end
        redirect_to products_path, notice: messageSuccess(:create)
    end

    ### action edit
    def edit      
        render :new
    end

    ### action update
    def update
        unless @product.update(product_params)
            flash.now[:notice] = messageFail(:create)
            return render :new
        end
        redirect_to products_path, notice: messageSuccess(:update)
    end

    ### action destroy
    def destroy
        message = messageFail(:destroy)
        message = messageSuccess(:destroy) if @product.destroy
        redirect_to products_path, notice: message
    end

    private

    ### product_params
    def product_params
        params.require(:product).permit(:title, :description, :price, :published, :category_id, :level, :country)
    end

    ### find_product
    def find_product
        @product = Product.find(params[:id])
    end

    ### message success
    def messageSuccess(action)
        "You have successfully #{action} the product"
    end

    ### message fail
    def messageFail(action)
        "There is an error when #{action}"    
    end  

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def new
      get_pre_login_url
      super
    end
    def create
      @referer_url = root_path
      super
    end
    def destroy
      @referer_url = root_path
      super
    end
    private
    def get_pre_login_url
      @referer_url = root_path
    end
    def after_sign_in_path_for resource
      sign_in_url = url_for(action: "new", controller: "sessions", only_path: false, protocol: "http")
      if @referer_url == sign_in_url
      super
    else
      @referer_url || root_path
    end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Ruby
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    
    - flash.each do |name, msg|
      = content_tag :div, msg, class: name
    .container
      - if notice
        p.alert.alert-success= notice
      - if alert
        p.alert.alert-danger= alert
      = yield

app/views/products/_product.html.slim
tr
  td= product.title
  td= product.description
  td= product.price
  td= product.category.try(:title)
  td= link_to "Details", product
  td
    = link_to "Edit", edit_product_path(product)
    = link_to "Delete", product_path(product), method: :delete, data:{confirm: 'Are you sure delete'}

app/views/products/index.html.slim
br
h2 = t(:product_list)

= link_to "Sign out", destroy_admin_session_path, :method => :delete

table.table.table-hover
  tr
    th Title
    th Description
    th Price
    th Titile of Product
    th Details
    th Action
  = render partial: 'product', collection: @products
= link_to "Create", new_product_url

app/views/products/new.html.slim
h2 Create Product
= semantic_form_for @product do |f|
  p Title: 
  = f.input :title
  p Description: 
  = f.input :description
  p Price: 
  = f.input :price, min: 0.01
  p Published: 
  = f.input :published
  p Category: 
  = f.input :category
  p Level: 
  = f.input :level
  p Country: 
  = f.input :country
  = f.action :submit

app/views/products/show.html.slim
h2 Show details product
p
  | Title: #{@product.title}
p
  | Description: #{@product.description}
p
  | Price: #{@product.price}
p
  | Published: #{@product.published}
p
  | Category id: #{@product.category_id}
p
  | Level: #{@product.level}
p
  | Country: #{@product.country}